cmake_minimum_required(VERSION 3.16)
project(PBO301_Pertemuan11 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_library(p11lib src/Vector3D.cpp src/SimpleStringLite.cpp)
target_include_directories(p11lib PUBLIC include)
target_compile_options(p11lib PRIVATE -Wall -Wextra -pedantic)
add_executable(pbo301_p11 src/main.cpp)
target_link_libraries(pbo301_p11 PRIVATE p11lib)
target_compile_options(pbo301_p11 PRIVATE -Wall -Wextra -pedantic)
enable_testing()
add_executable(test_p11 tests/test_main.cpp)
target_link_libraries(test_p11 PRIVATE p11lib)
target_compile_options(test_p11 PRIVATE -Wall -Wextra -pedantic)
add_test(NAME p11_tests COMMAND test_p11)
